### PR TITLE
Update meshtastic-js to newer protobuf spec

### PR DESCRIPTION
**Pull request by johnlaur**
Closes: https://github.com/meshtastic/js/issues/96

This PR bumps package versions; most importantly `@buf/meshtastic_protobufs.bufbuild_es`

The factory reset API has since been refactored into separate reset device and reset config instructions. I updated the function names to match which removes the previously available `factoryReset()` API. If there is a desire to maintain backwards compatibility, `factoryReset()` could be aliased to `factoryResetDevice()`.

I have also not incremented the meshtastic-js version number as defined in package.json.

### CODE REVIEW

**Comment by Hunter275** [comment]
@johnlaur 

Build error:
`ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json`

Please include the `pnpm-lock.yaml` file in your PR

**Comment by johnlaur** [comment]
Sorry I am new to pnpm. I will figure that out and post a fix.

**Comment by Hunter275** [comment]
> Sorry I am new to pnpm. I will figure that out and post a fix.

No problem. You shouldn't need to do anything except commit that file to the branch.

**Comment by johnlaur** [comment]
Hey thank you for the merge and sorry for the delay;  I was just able to get back to look at this today. I do have pnpm set up now.

**Pull request merged**
