### PR TITLE
Revert serial

### PR DESCRIPTION
**Pull request by Hunter275**
Revert serial

### CODE REVIEW

**Review by thebentern — APPROVED** [review]

**Comment by benbrown** [comment]
I am learning from reading the commit history -- why did this happen?

**Comment by nmaq-dev** [comment]
I have the same question! Why???

I've spent the last few hours trying to figure out how to accomplish this. 

I ran across this issue in the python code https://github.com/meshtastic/python/pull/74 which brought me here. I had looked in this repo for anything that was server-attached instead of browser-attached.

**Comment by benbrown** [comment]
@nmaq-dev  this branch has a working node implementation https://github.com/meshtastic/js/pull/119

**Comment by nmaq-dev** [comment]
Thanks for that :bow: 

I'll poke at things. I started on the python side of things because I know it far better than js/ts/node. I can give it a shot and see if I can contribute any thoughts.

**Comment by Hunter275** [comment]
> @nmaq-dev The reason is that bundling the node dependencies causes issues when used in a browser unless you do extra build steps yourself which is a recipe for pain. I have some PRs open around this, but I think the likely path forward will be a separate module to handle nodejs connections rather than including them both in this package.

Exactly this.

**Comment by benbrown** [comment]
@Hunter275 glad I got it right. I've got the working node class, I just need to bundle it up into a separate package.

**Pull request merged**
