### PR TITLE
feat: Add functionality to connect to serial via NodeJS

### PR DESCRIPTION
**Pull request by TheCyberRonin**
This PR will:

-  Add `NodeSerialConnection` and `nodeTransformHandler`
   - These work in tandem to connect to a device via serial using NodeJS
   - `serialport` was added as a dependency for this as well
- Add example JS file to show it being used

I can send and receive packets and data using this code. There is a lot to test out and I'm hoping people can use this to poke holes. This shouldn't have an impact on any of the other connection types.

This should do the trick for #86
solves #83

### CODE REVIEW

**Comment by TheCyberRonin** [comment]
I'll fix up that space on a newline so the linter is happy tonight

**Comment by sachaw** [comment]
Thanks for the PR.
I eventually want to publish a single cross-platform fore package and additional transport adapter's but this can definitely happen after merging this.
Let me know when you're ready to merge.

**Comment by TheCyberRonin** [comment]
> Thanks for the PR. I eventually want to publish a single cross-platform fore package and additional transport adapter's but this can definitely happen after merging this. Let me know when you're ready to merge.

Are there any GitHub Projects or future plans that I could help tackle? During this work, I noticed that there are packets being ignored that seem to have Bluetooth start sequences. I was planning on tackling some of the packet types that aren't yet being parsed.

I think after that version bump, I appeased the GitHub Actions gods. As long as everyone is ok with this change, I think it's good to merge. If any issues arise with this code, I'll gladly work on improving it and bugfix.

**Review by Hunter275 — APPROVED** [review]

**Review by thebentern — APPROVED** [review]

**Comment by Hunter275** [comment]
@sachaw just waiting on your review and I think this can be merged. I can also merge it if you want.

**Pull request merged**
